name: Publish to PyPI.org
on:
  release:
    types: [published]
jobs:
  gha-release-and-pypi-release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: |
          fetch-depth: 0
          python-version: "3.x"
 
      #- run: python3 -m pip install --upgrade build && python3 -m build

      - name: Install dependencies
        run: |
          python -m pip install --upgrade build
          #pip install setuptools wheel twine
          python -m build

      - name: Build the dist files
         run: python setup.py sdist bdist_wheel
 
      - name: Publish distribution(package) to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: Vijaik
          password: ${{ secrets.RELE_VER_PYPI_API_TOKEN }}   
          skip-existing: true

